// generalData.js
const permisosData = [
  {
    id: 1,
    group: "Extrusores",
    permisos: "extrusores.mostrar",
    text_font: "Mostrar todos las Etiquetas",
    descripcion: "",
  },
  {
    id: 2,
    group: "Extrusores",
    permisos: "extrusores.crear",
    text_font: "Crear las Etiquetas",
    descripcion: "",
  },
  {
    id: 3,
    group: "Extrusores",
    permisos: "extrusores.editar",
    text_font: "Editar las Etiquetas",
    descripcion: "",
  },
  {
    id: 4,
    group: "Extrusores",
    permisos: "extrusores.pendiente",
    text_font: "Pendientes las Etiquetas",
    descripcion: "",
  },
  {
    id: 5,
    group: "Extrusores",
    permisos: "extrusores.extruir",
    text_font: "Extruir las Etiquetas",
    descripcion: "",
  },
  {
    id: 6,
    group: "Extrusores",
    permisos: "extrusores.exportacion",
    text_font: "Importar excel",
    descripcion: "",
  },
  {
    id: 7,
    group: "Extrusores",
    permisos: "extrusores.mover",
    text_font: "Mover las Etiquetas",
    descripcion: "",
  },
  {
    id: 8,
    group: "Productos",
    permisos: "productos.mostrar",
    text_font: "Mostrar todos las Productos",
    descripcion: "",
  },
  {
    id: 9,
    group: "Productos",
    permisos: "productos.crear",
    text_font: "Crear las Productos",
    descripcion: "",
  },
  {
    id: 10,
    group: "Productos",
    permisos: "productos.editar",
    text_font: "Editar las Productos",
    descripcion: "",
  },
  {
    id: 11,
    group: "Productos",
    permisos: "productos.eliminar",
    text_font: "Eliminar las Productos",
    descripcion: "",
  },
  {
    id: 12,
    group: "Productos",
    permisos: "productos.exportacion",
    text_font: "Importar excel",
    descripcion: "",
  },
  {
    id: 13,
    group: "Productos_estruidos",
    permisos: "productos_estruidos.mostrar",
    text_font: "Mostrar todos las Etiquetas",
    descripcion: "",
  },
];

export default permisosData;
